### ISSUE TITLE
IssueTemplate.html not working

### ISSUE THREAD

**Issue by davelab6** [LivelyKernel/lively-web.org#1]
http://lively-web.org/issues/IssueTemplate.html seems not to work at showing all issues

Operating system OS X 10.11.3
Javascript enabled Yes
Cookies enabled Yes
Flash version 21.0.0
Java version Not installed
Websockets supported Yes
Browser size 1570 x 866
Screen size 1680 x 1050 (Retina)
Color depth 24 bit

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2710.0 Safari/537.36

**Comment by rksm** [comment]
Thanks for reporting, should be fixed now.

**Comment by davelab6** [comment]
👍
